<?php

namespace Database\Seeders;

use App\Models\Parameter;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ParameterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        parameter::create(['grp' => 'STATUS', 'subgrp' => 'STATUS', 'kelompok' => '', 'text' => 'AKTIF', 'memo' => '{"MEMO":"AKTIF","SINGKATAN":"A","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'STATUS', 'subgrp' => 'STATUS', 'kelompok' => '', 'text' => 'NON AKTIF', 'memo' => '{"MEMO":"NON AKTIF","SINGKATAN":"NA","WARNA":"#6C757D"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'STATUS AKSES', 'subgrp' => 'STATUS AKSES', 'kelompok' => '', 'text' => 'PUBLIC', 'memo' => '{"MEMO":"PUBLIC","SINGKATAN":"P","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'STATUS AKSES', 'subgrp' => 'STATUS AKSES', 'kelompok' => '', 'text' => 'PRIVATE', 'memo' => '{"MEMO":"PRIVATE","SINGKATAN":"V","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'JENIS ARMADA', 'subgrp' => 'JENIS ARMADA', 'kelompok' => '', 'text' => 'MOTOR', 'memo' => '{"MEMO":"MOTOR","SINGKATAN":"MT","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'JENIS ARMADA', 'subgrp' => 'JENIS ARMADA', 'kelompok' => '', 'text' => 'PICKUP', 'memo' => '{"MEMO":"PICKUP","SINGKATAN":"PK","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'JENIS ARMADA', 'subgrp' => 'JENIS ARMADA', 'kelompok' => '', 'text' => 'BECAK', 'memo' => '{"MEMO":"BECAK","SINGKATAN":"BC","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'TIPE BANK', 'subgrp' => 'TIPE BANK', 'kelompok' => '', 'text' => 'BANK', 'memo' => '{"MEMO":"BANK","SINGKATAN":"B","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'TIPE BANK', 'subgrp' => 'TIPE BANK', 'kelompok' => '', 'text' => 'KAS      ', 'memo' => '{"MEMO":"KAS","SINGKATAN":"K","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'TIPE BANK', 'subgrp' => 'TIPE BANK', 'kelompok' => '', 'text' => 'GIRO', 'memo' => '{"MEMO":"GIRO","SINGKATAN":"G","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'TOP', 'subgrp' => 'TOP', 'kelompok' => '', 'text' => 'CASH', 'memo' => '{"MEMO":"CASH","SINGKATAN":"CASH","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'TOP', 'subgrp' => 'TOP', 'kelompok' => '', 'text' => 'CREDIT', 'memo' => '{"MEMO":"CREDIT","SINGKATAN":"CREDIT","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'PESANAN HEADER BUKTI', 'subgrp' => 'PESANAN HEADER BUKTI', 'kelompok' => '', 'text' => '#PS #9999#/#R#/#Y', 'memo' => '{"MEMO":"PESANAN HEADER BUKTI","SINGKATAN":"#PS #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff","BATASWAKTUEDIT":"5"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'PESANAN FINAL HEADER BUKTI', 'subgrp' => 'PESANAN FINAL HEADER BUKTI', 'kelompok' => '', 'text' => '#PF #9999#/#R#/#Y', 'memo' => '{"MEMO":"PESANAN FINAL HEADER BUKTI","SINGKATAN":"#PF #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff","BATASWAKTUEDIT":"5"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'PENJUALAN HEADER BUKTI', 'subgrp' => 'PENJUALAN HEADER BUKTI', 'kelompok' => '', 'text' => '#J #9999#/#R#/#Y', 'memo' => '{"MEMO":"PENJUALAN HEADER BUKTI","SINGKATAN":"#J #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff","BATASWAKTUEDIT":"5"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'HARGA PRODUCT', 'subgrp' => 'HARGA PRODUCT', 'kelompok' => '', 'text' => 'HARGA JUAL', 'memo' => '{"MEMO":"HARGA JUAL","SINGKATAN":"HARGA JUAL","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'HARGA PRODUCT', 'subgrp' => 'HARGA PRODUCT', 'kelompok' => '', 'text' => 'HARGA KONTRAK 1', 'memo' => '{"MEMO":"HARGA KONTRAK 1","SINGKATAN":"HARGA KONTRAK 1","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'HARGA PRODUCT', 'subgrp' => 'HARGA PRODUCT', 'kelompok' => '', 'text' => 'HARGA KONTRAK 2', 'memo' => '{"MEMO":"HARGA KONTRAK 2","SINGKATAN":"HARGA KONTRAK 2","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'HARGA PRODUCT', 'subgrp' => 'HARGA PRODUCT', 'kelompok' => '', 'text' => 'HARGA KONTRAK 3', 'memo' => '{"MEMO":"HARGA KONTRAK 3","SINGKATAN":"HARGA KONTRAK 3","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'HARGA PRODUCT', 'subgrp' => 'HARGA PRODUCT', 'kelompok' => '', 'text' => 'HARGA KONTRAK 4', 'memo' => '{"MEMO":"HARGA KONTRAK 4","SINGKATAN":"HARGA KONTRAK 4","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'HARGA PRODUCT', 'subgrp' => 'HARGA PRODUCT', 'kelompok' => '', 'text' => 'HARGA KONTRAK 5', 'memo' => '{"MEMO":"HARGA KONTRAK 5","SINGKATAN":"HARGA KONTRAK 5","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'HARGA PRODUCT', 'subgrp' => 'HARGA PRODUCT', 'kelompok' => '', 'text' => 'HARGA KONTRAK 6', 'memo' => '{"MEMO":"HARGA KONTRAK 6","SINGKATAN":"HARGA KONTRAK 6","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'TAX', 'subgrp' => 'TAX', 'kelompok' => '', 'text' => '0', 'memo' => '{"MEMO":"TAX","SINGKATAN":"TAX","WARNA":"#28A745","WARNATULISAN":"#fff"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'PEMBELIAN HEADER BUKTI', 'subgrp' => 'PEMBELIAN HEADER BUKTI', 'kelompok' => '', 'text' => '#B #9999#/#R#/#Y', 'memo' => '{"MEMO":"PEMBELIAN HEADER BUKTI","SINGKATAN":"#B #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff","BATASWAKTUEDIT":"5"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'HUTANG BUKTI', 'subgrp' => 'HUTANG BUKTI', 'kelompok' => '', 'text' => '#H #9999#/#R#/#Y', 'memo' => '{"MEMO":"HUTANG BUKTI","SINGKATAN":"#H #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'PIUTANG BUKTI', 'subgrp' => 'PIUTANG BUKTI', 'kelompok' => '', 'text' => '#P #9999#/#R#/#Y', 'memo' => '{"MEMO":"PIUTANG BUKTI","SINGKATAN":"#P #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'KODE KARTU STOK', 'subgrp' => 'KODE KARTU STOK', 'kelompok' => '', 'text' => 'JUAL', 'memo' => '{"MEMO":"JUAL","SINGKATAN":"J","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'KODE KARTU STOK', 'subgrp' => 'KODE KARTU STOK', 'kelompok' => '', 'text' => 'BELI', 'memo' => '{"MEMO":"BELI","SINGKATAN":"B","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'KODE KARTU STOK', 'subgrp' => 'KODE KARTU STOK', 'kelompok' => '', 'text' => 'RETUR JUAL', 'memo' => '{"MEMO":"RETUR JUAL","SINGKATAN":"RJ","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'KODE KARTU STOK', 'subgrp' => 'KODE KARTU STOK', 'kelompok' => '', 'text' => 'RETUR BELI', 'memo' => '{"MEMO":"RETUR BELI","SINGKATAN":"RB","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'STATUS2', 'subgrp' => 'STATUS2', 'kelompok' => '', 'text' => 'MODIFIED', 'memo' => '{"MEMO":"MODIFIED","SINGKATAN":"M","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'STATUS2', 'subgrp' => 'STATUS2', 'kelompok' => '', 'text' => 'COMBINE', 'memo' => '{"MEMO":"COMBINE","SINGKATAN":"C","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'CEK PESANAN', 'subgrp' => 'CEK PESANAN', 'kelompok' => '', 'text' => 'CEK PESANAN', 'memo' => '{"MEMO":"CEK PESANAN","SINGKATAN":"CP","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'JENIS PELUNASAN', 'subgrp' => 'JENIS PELUNASAN', 'kelompok' => '', 'text' => 'BANK/KAS', 'memo' => '{"MEMO":"BANK/KAS","SINGKATAN":"B/K","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'JENIS PELUNASAN', 'subgrp' => 'JENIS PELUNASAN', 'kelompok' => '', 'text' => 'NOTA DEBET', 'memo' => '{"MEMO":"NOTA DEBET","SINGKATAN":"NB","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'CEK PESANAN DETAIL', 'subgrp' => 'CEK PESANAN DETAIL', 'kelompok' => '', 'text' => 'CEK PESANAN DETAIL', 'memo' => '{"MEMO":"CEK PESANAN DETAIL","SINGKATAN":"&#10003;","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'RESET PENOMORAN', 'subgrp' => 'RESET PENOMORAN', 'kelompok' => '', 'text' => 'RESET BULAN', 'memo' => '{"MEMO":"RESET BULAN","SINGKATAN":"RB","WARNA":"#28A745","WARNATULISAN":"#FFF"}', 'type' => '0', 'default' => 'YA',  'modifiedby' => 'ADMIN',]);
        parameter::create(['grp' => 'RESET PENOMORAN', 'subgrp' => 'RESET PENOMORAN', 'kelompok' => '', 'text' => 'RESET TAHUN', 'memo' => '{"MEMO":"RESET TAHUN","SINGKATAN":"RT","WARNA":"#6C757D","WARNATULISAN":"#FFF"}', 'type' => '0', 'default' => '',  'modifiedby' => 'ADMIN',]);
        parameter::create(['grp' => 'PELUNASAN HUTANG HEADER BUKTI', 'subgrp' => 'PELUNASAN HUTANG HEADER BUKTI', 'kelompok' => '', 'text' => '#PH #9999#/#R#/#Y', 'memo' => '{"MEMO":"PELUNASAN HUTANG HEADER BUKTI","SINGKATAN":"#PH #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'BATAS WAKTU EDIT', 'subgrp' => 'BATAS WAKTU EDIT', 'kelompok' => '', 'text' => 'BATAS WAKTU EDIT', 'memo' => '{"MEMO":"BATAS WAKTU EDIT","SINGKATAN":"BWE","WARNA":"#6C757D","WARNATULISAN":"#FFF","BATASWAKTUEDIT":"5"}', 'type' => '0', 'default' => '',  'modifiedby' => 'ADMIN',]);
        parameter::create(['grp' => 'PELUNASAN PIUTANG HEADER BUKTI', 'subgrp' => 'PELUNASAN PIUTANG HEADER BUKTI', 'kelompok' => '', 'text' => '#PP #9999#/#R#/#Y', 'memo' => '{"MEMO":"PELUNASAN PIUTANG HEADER BUKTI","SINGKATAN":"#PP #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'OPERATOR', 'subgrp' => 'OPERATOR', 'kelompok' => '', 'text' => 'TAMBAH', 'memo' => '{"MEMO":"TAMBAH","SINGKATAN":"+","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'OPERATOR', 'subgrp' => 'OPERATOR', 'kelompok' => '', 'text' => 'KURANG', 'memo' => '{"MEMO":"KURANG","SINGKATAN":"-","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'GROUP  ', 'subgrp' => 'GROUP PERKIRAAN', 'kelompok' => '', 'text' => 'BELANJA', 'memo' => '{"MEMO":"BELANJA","SINGKATAN":"B","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'GROUP PERKIRAAN', 'subgrp' => 'GROUP PERKIRAAN', 'kelompok' => '', 'text' => 'ARMADA', 'memo' => '{"MEMO":"ARMADA","SINGKATAN":"A","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'RETUR JUAL HEADER BUKTI', 'subgrp' => 'RETUR JUAL HEADER BUKTI', 'kelompok' => '', 'text' => '#RJ #9999#/#R#/#Y', 'memo' => '{"MEMO":"RETUR JUAL HEADER BUKTI","SINGKATAN":"#RJ #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff","BATASWAKTUEDIT":"5"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'RETUR BELI HEADER BUKTI', 'subgrp' => 'RETUR BELI HEADER BUKTI', 'kelompok' => '', 'text' => '#RB #9999#/#R#/#Y', 'memo' => '{"MEMO":"RETUR BELI HEADER BUKTI","SINGKATAN":"#RB #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff","BATASWAKTUEDIT":"5"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'PENYESUAIAN STOK HEADER BUKTI', 'subgrp' => 'PENYESUAIAN STOK HEADER BUKTI', 'kelompok' => '', 'text' => '#PST #9999#/#R#/#Y', 'memo' => '{"MEMO":"PENYESUAIAN STOK HEADER BUKTI","SINGKATAN":"#PST #9999#/#R#/#Y","WARNA":"#28A745","WARNATULISAN":"#fff","BATASWAKTUEDIT":"5"}', 'type' => '37', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'JENIS HUTANG PIUTANG', 'subgrp' => 'JENIS HUTANG PIUTANG', 'kelompok' => '', 'text' => 'BELUM LUNAS', 'memo' => '{"MEMO":"BELUM LUNAS","SINGKATAN":"BL","WARNA":"#28A745","WARNATULISAN":"#fff"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'JENIS HUTANG PIUTANG', 'subgrp' => 'JENIS HUTANG PIUTANG', 'kelompok' => '', 'text' => 'LUNAS', 'memo' => '{"MEMO":"LUNAS","SINGKATAN":"L","WARNA":"#28A745","WARNATULISAN":"#fff"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
        parameter::create(['grp' => 'BATAS AWAL TAHUN', 'subgrp' => 'BATAS AWAL TAHUN', 'kelompok' => '', 'text' => '01-01-2004', 'memo' => '{"MEMO":"01-01-2004","SINGKATAN":"BAT","WARNA":"#28A745","WARNATULISAN":"#FFF"}', 'type' => '0', 'default' => 'YA',  'modifiedby' => 'ADMIN',]);
        parameter::create(['grp' => 'PERKIRAAN', 'subgrp' => 'PERKIRAAN', 'kelompok' => '', 'text' => 'PARENT', 'memo' => '{"MEMO":"PARENT","SINGKATAN":"P","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => 'YA',]);
        parameter::create(['grp' => 'PERKIRAAN', 'subgrp' => 'PERKIRAAN', 'kelompok' => '', 'text' => 'BUKAN PARENT', 'memo' => '{"MEMO":"BUKAN PARENT","SINGKATAN":"BP","WARNA":"#28A745"}', 'type' => '0', 'modifiedby' => 'ADMIN', 'default' => '',]);
    }
}
